HoroscopePredictorApp/Controllers/HoroscopeController.cs
using HoroscopePredictorApp.Data_Access;
using HoroscopePredictorApp.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HoroscopePredictorApp.Controllers
{
    [Authorize]
    public class HoroscopeController : Controller
    {
      
        private readonly IHoroscopePredictorAPIClient _horoscopeAPI;
        public HoroscopeController(IHoroscopePredictorAPIClient horoscopePredictorAPI)
        {
          
            _horoscopeAPI = horoscopePredictorAPI;
        }
        public IActionResult Index()
        {
            return View();
        }

       
        public IActionResult DateOfBirth()
        {
            return View();
        }

        [HttpPost]
        public IActionResult DateOfBirth(DateOfBirthViewModel model)
        {
            if (ModelState.IsValid)
            {
                return RedirectToAction(nameof(DetailsByDob), new
                {
                    dateOfBirth = model.DateOfBirth,
                    day = model.Day.ToString().ToLower()
                });
            }
            return View();

        }

        [HttpGet("horoscope/byDob")]
        public async Task<IActionResult> DetailsByDob([FromQuery] DateTime dateOfBirth, [FromQuery] string day)
        {

            var model = await _horoscopeAPI.GetHoroscopeDataFromDateOfBirthAsync(dateOfBirth, day);
            return View("HoroscopePrediction",model);
        }


        public IActionResult Zodiac()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Zodiac(ZodiacViewModel zodiacSign)
        {
            if (ModelState.IsValid)
            {
                return RedirectToAction(nameof(DetailsByZodiac), new
                {
                    zodiac = zodiacSign.Zodiac.ToString(),
                    day = zodiacSign.Day.ToString().ToLower()
                });
            }
            return View();
        }

        [HttpGet("horoscope/zodiac/{zodiac}")]
        public async Task<IActionResult> DetailsByZodiac(string zodiac, [FromQuery] string day)
        {
            var model = await _horoscopeAPI.GetHoroscopeDataFromZodiacAsync(zodiac, day);
            return View("HoroscopePrediction",model);
        }
    }
}

HoroscopePredictorApp/Controllers/UserController.cs
using HoroscopePredictorApp.Data_Access;
using HoroscopePredictorApp.Models;
using HoroscopePredictorApp.Services;
using HoroscopePredictorApp.ViewModels;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Refit;
using System.Security.Claims;
using System.IdentityModel.Tokens.Jwt;

namespace HoroscopePredictorApp.Controllers
{
    public class UserController : Controller
    {
        private readonly IHoroscopePredictorAPIClient _horoscopePredictorAPIClient;
        private readonly ITokenService _tokenService;

        public UserController(IHoroscopePredictorAPIClient horoscopePredictorAPIClient, ITokenService tokenService)
        {
            _horoscopePredictorAPIClient = horoscopePredictorAPIClient;
            _tokenService = tokenService;
        }
        [HttpGet]
        public IActionResult Register()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
        


        [HttpGet]
        public IActionResult Login()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }


            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var user = new RegisterUser
                    {
                        Name = model.Name,
                        Email = model.Email,
                        Password = model.Password,
                    };
                    var result = await _horoscopePredictorAPIClient.Register(user);
                    if(result.StatusCode == System.Net.HttpStatusCode.Created)
                    {
                    return RedirectToAction(nameof(Login), nameof(User));

                    }

                }
            }
            catch (ApiException ex)
            {
                RegisterUserResponseModel? error = await ex.GetContentAsAsync<RegisterUserResponseModel>();

                ViewBag.HasLoginFailed = true;
                ViewBag.LoginErrorMessage = error?.Message;
                return View();

            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginUser model,string? returnUrl)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    LoginUserResponseModel result = await _horoscopePredictorAPIClient.Login(model);
                    if (result.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        _tokenService.SetAccessToken(result.JwtToken);
                        var jwtHandler = new JwtSecurityTokenHandler();
                        List<Claim> claims = jwtHandler.ReadJwtToken(result.JwtToken).Claims.ToList();
                        var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                        var claimsPrincipal = new ClaimsPrincipal(claimsIdentity);
                        await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, claimsPrincipal, new AuthenticationProperties
                        {
                            IsPersistent = false,
                            ExpiresUtc= DateTime.UtcNow.AddDays(1)
                        });
                        if(!string.IsNullOrEmpty(returnUrl) && Url.IsLocalUrl(returnUrl))
                        {
                            return Redirect(returnUrl);
                        }
                        return RedirectToAction(nameof(Index), "Home");
                    }

                }

            }
            catch (ApiException ex)
            {
                LoginUserResponseModel? error = await ex.GetContentAsAsync<LoginUserResponseModel>();

                ViewBag.HasLoginFailed = true;
                ViewBag.LoginErrorMessage = error?.Message;
                return View();


            }
            return View();
        }

        [Microsoft.AspNetCore.Authorization.Authorize]
        [HttpGet]
        public async Task<IActionResult> History()
        {
            var zodiacHistory = await _horoscopePredictorAPIClient.History();
            return View(zodiacHistory);
        }

        [HttpPost]
        public IActionResult Logout()
        {
            HttpContext.Response.Cookies.Delete("token");
            HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction(nameof(Login));
        }
    }
}

HoroscopePredictorApp/Views/Shared/NotFound.cshtml
@{
    ViewBag.Title = "Not Found";
}

<h1>@ViewBag.ErrorMessage</h1>


<a asp-action="index" asp-controller="home">
    Click here to navigate to the home page
</a>

HoroscopePredictorApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="preload" href="https://fonts.googleapis.com/css2?family=Agbalumo&family=Poppins&display=swap" as="font" type="font/woff2" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Agbalumo&family=Poppins&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm bg-dark border-bottom border-body box-shadow mb-3" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">AstroVista</a>
                <button class="navbar-toggler navbar-dark" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon "></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Horoscope" asp-action="Index">Horoscope</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="User" asp-action="History">History</a>
                            </li>                            
                        }
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <form method="post" asp-action="logout" asp-controller="user">
                                <button type="submit" class="nav-link text-light logout-btn-color">Logout - @User.Identity.Name</button>
                            </form>
                        }
                        else{
                        <li class="nav-item">
                            <a asp-action="register" asp-controller="user" class="nav-link text-light">Register</a>
                        </li>
                        <li class="nav-item">
                            <a asp-action="login" asp-controller="user" class="nav-link text-light">Login</a>
                        </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container" >
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>


    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>